import './globals.css'
import { Manrope } from 'next/font/google'


const inter = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'The Thoughtful Pen',
  description: 'Generated by Rakibul',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className='mx-40'>

          {children}

        </div>
      </body>
    </html>
  )
}
