import Navbar from '@/components/Navbar'
import './globals.css'
import { Manrope } from 'next/font/google'
import Footer from '@/components/Footer'
import Providers from '@/components/Providers'
import AuthProvider from '@/components/AuthProvider'
import { Analytics } from '@vercel/analytics/react';

const inter = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'The Thoughtful Pen',
  description: 'Generated by Rakibul',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <div className='mx-40'>
              <Navbar />
              {children}
              <Analytics />
              <Footer />
            </div>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  )
}
