import '../globals.css'
import DashboardNavbar from '@/components/DashboardNavbar'

export const metadata = {
	title: 'Dashboard',
	description: 'Generated by Rakibul',
}

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div className='h-screen mx-40'>
			<div className="flex flex-row gap-x-4">
				<div className="w-1/4 min-h-screen p-4 rounded-md bg-slate-400">
					<DashboardNavbar />
				</div>
				<div className="w-3/4">
					{children}
				</div>
			</div>
		</div>
	)
}
