import '../globals.css'
import { Manrope } from 'next/font/google'
import DashboardNavbar from '@/components/DashboardNavbar'


const inter = Manrope({ subsets: ['latin'] })

export const metadata = {
	title: 'Dashboard',
	description: 'Generated by Rakibul',
}

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div className={inter.className}>
			<div className="flex flex-row gap-4 h-screen mx-[40px] my-[40px]">
				<div className="flex w-3/12 p-10 rounded-md bg-slate-200">
					<DashboardNavbar />
				</div>
				<div className="flex w-9/12">
					{children}
				</div>
			</div>
		</div>
	)
}
